# Generated by Django 5.2.4 on 2025-07-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyzeddata',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='analyzeddata',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
