# Generated by Django 5.2.4 on 2025-07-10 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_rename_uploaded_at_analyzeddata_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzeddata',
            name='diagram_paths',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analyzeddata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
