# Generated by Django 5.2.4 on 2025-08-14 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0004_analysisactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzeddata',
            name='user',
        ),
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='datasets/original/')),
                ('cleaned_file', models.FileField(blank=True, null=True, upload_to='datasets/cleaned/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rows_count', models.IntegerField(blank=True, null=True)),
                ('columns_count', models.IntegerField(blank=True, null=True)),
                ('missing_values_count', models.IntegerField(blank=True, null=True)),
                ('duplicates_count', models.IntegerField(blank=True, null=True)),
                ('outliers_count', models.IntegerField(blank=True, null=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('report_html', models.FileField(blank=True, null=True, upload_to='reports/html/')),
                ('graphs_zip', models.FileField(blank=True, null=True, upload_to='reports/graphs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(max_length=50)),
                ('column_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('value', models.JSONField(blank=True, null=True)),
                ('importance_score', models.FloatField(default=0.0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='analyze.dataanalysis')),
            ],
            options={
                'ordering': ['-importance_score'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_type', models.CharField(choices=[('histogram', 'Histogram'), ('boxplot', 'Box Plot'), ('scatter', 'Scatter Plot'), ('correlation', 'Correlation Heatmap'), ('countplot', 'Count Plot'), ('pairplot', 'Pair Plot'), ('timeseries', 'Time Series')], max_length=50)),
                ('column_names', models.JSONField()),
                ('file_path', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='analyze.dataanalysis')),
            ],
            options={
                'ordering': ['graph_type', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='AnalysisActivity',
        ),
        migrations.DeleteModel(
            name='AnalyzedData',
        ),
    ]
