# Generated by Django 5.2.4 on 2025-08-16 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0005_remove_analyzeddata_user_dataanalysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisinsight',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dataanalysis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generatedgraph',
            options={},
        ),
        migrations.RemoveField(
            model_name='analysisinsight',
            name='column_name',
        ),
        migrations.RemoveField(
            model_name='analysisinsight',
            name='description',
        ),
        migrations.RemoveField(
            model_name='analysisinsight',
            name='importance_score',
        ),
        migrations.RemoveField(
            model_name='analysisinsight',
            name='insight_type',
        ),
        migrations.RemoveField(
            model_name='analysisinsight',
            name='value',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='columns_count',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='dataset_name',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='duplicates_count',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='graphs_zip',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='missing_values_count',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='outliers_count',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='report_html',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='report_pdf',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='rows_count',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='generatedgraph',
            name='column_names',
        ),
        migrations.RemoveField(
            model_name='generatedgraph',
            name='description',
        ),
        migrations.RemoveField(
            model_name='generatedgraph',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='generatedgraph',
            name='graph_type',
        ),
        migrations.RemoveField(
            model_name='generatedgraph',
            name='title',
        ),
        migrations.AddField(
            model_name='analysisinsight',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisinsight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='graph_image',
            field=models.ImageField(blank=True, null=True, upload_to='graphs/'),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='graph_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='cleaned_file',
            field=models.FileField(blank=True, null=True, upload_to='cleaned/'),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='original_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
