# Generated by Django 5.2.4 on 2025-08-16 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0007_dataanalysis_dataset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
