# Generated by Django 5.2.4 on 2025-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0008_alter_dataanalysis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinsight',
            name='importance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='graph_type',
            field=models.CharField(choices=[('histogram', 'Histogram'), ('boxplot', 'Box Plot'), ('scatter', 'Scatter Plot'), ('correlation', 'Correlation Heatmap'), ('countplot', 'Count Plot'), ('pairplot', 'Pair Plot'), ('timeseries', 'Time Series')], default='histogram', max_length=50),
        ),
    ]
