# Generated by Django 5.2.4 on 2025-08-18 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0009_analysisinsight_importance_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisinsight',
            options={'ordering': ['-importance_score']},
        ),
        migrations.AlterModelOptions(
            name='dataanalysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='generatedgraph',
            options={'ordering': ['graph_type', 'title']},
        ),
        migrations.RemoveField(
            model_name='analysisinsight',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='generatedgraph',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='generatedgraph',
            name='graph_image',
        ),
        migrations.RemoveField(
            model_name='generatedgraph',
            name='graph_name',
        ),
        migrations.AddField(
            model_name='analysisinsight',
            name='column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysisinsight',
            name='insight_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analysisinsight',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='columns_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='duplicates_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='graphs_zip',
            field=models.FileField(blank=True, null=True, upload_to='reports/graphs/'),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='missing_values_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='outliers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='report_html',
            field=models.FileField(blank=True, null=True, upload_to='reports/html/'),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/pdf/'),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='rows_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='column_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='cleaned_file',
            field=models.FileField(blank=True, null=True, upload_to='datasets/cleaned/'),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='datasets/original/'),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generatedgraph',
            name='graph_type',
            field=models.CharField(choices=[('histogram', 'Histogram'), ('boxplot', 'Box Plot'), ('scatter', 'Scatter Plot'), ('correlation', 'Correlation Heatmap'), ('countplot', 'Count Plot'), ('pairplot', 'Pair Plot'), ('timeseries', 'Time Series')], max_length=50),
        ),
    ]
