# Generated by Django 5.2.4 on 2025-08-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0010_alter_analysisinsight_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisinsight',
            old_name='content',
            new_name='description',
        ),
    ]
