# Generated by Django 5.2.4 on 2025-08-18 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_display_name_profile_bio_and_more'),
        ('analyze', '0011_rename_content_analysisinsight_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
