# Generated by Django 5.2.4 on 2025-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0012_alter_dataanalysis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedgraph',
            name='graph_file',
            field=models.FileField(blank=True, null=True, upload_to='graphs/'),
        ),
    ]
